/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import { BluetoothService, MagnetometerService, LocationService, SampleUI} from 'react-native-private-kit-sdk';

export default class App extends Component {
  constructor(props) {
    super(props);
    this.startServices();
  }

  startBluetoothService() {
    // Use the permissions check code here
    BluetoothService.init();
    BluetoothService.requestBluetoothStatus();
    BluetoothService.enableBT();
    BluetoothService.start();
  }

  startMagnetometerService() {
    MagnetometerService.start();
  }

  startLocationService() {
    // Use the permissions check code here
    let locationPermission = LocationService.checkLocationPermission()
    if (locationPermission == false) {
      LocationService.requestLocation();
    }
    LocationService.start();
  }

  startServices() {
    console.log("start services")
    this.startBluetoothService();
    this.startLocationService();
    this.startMagnetometerService();
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆PrivateKitSdk example☆</Text>
        <Text style={styles.instructions}>STATUS: loaded</Text>
        <Text style={styles.welcome}>☆☆☆</Text>
        <SampleUI />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
